import type { Metadata } from "next";
import "./globals.css";

import { Pirata_One } from "next/font/google";

const pirata = Pirata_One({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pirata.className}>{children}</body>
    </html>
  );
}
